# Generated by Django 5.0.6 on 2024-05-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='second',
            new_name='last',
        ),
    ]
